# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '.github/workflows/build.yml'      
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: 

  BUILD_PLATFORMS: x64 x86 ARM64

  BUILD_CONFIGURATIONS: Release Debug

  MSBUILD_EXTRA_OPTIONS: -noWarn:MSB4011 -ds:true
 
  VCPKGCACHE_PATH: vcpkg-caches
  
  TARGET_VCPKG_MANIFEST_INSTALL: VcpkgInstallManifestDependencies

  #enable multiprocess compiling with MSVC
  CL_: /MP

    # This is set to "IMAGE_VERSION-{Xored MD5 Hashes of both vcpkg json files in the repository}" by the Initial Setup step
  # This is used to track when a change happens that should trigger cleaning of the cache and discarding old files
  CACHE_KEY:

    # has of the files being cached.
  VCPKG_CACHE_HASH:


permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.runner }}
 

    strategy:
      max-parallel: 1 # force them to run sequentially
      fail-fast: true
      matrix:
        runner: [windows-2022, windows-11-arm]    


    env:
     #Vcpkg caches, Each platform writes to its own cache but can read from the Windows 2022 cache

     # use a script for the asset cache
      X_VCPKG_ASSET_SOURCES: ${{format('clear;x-script,{0}\vcpkg-caches\asset-cache-script.bat {{url}} {{sha512}} {{dst}};x-azurl,file://{0}\vcpkg-caches\{1}\asset,,write', github.workspace, github.workspace,matrix.runner) }}

      VCPKG_BINARY_SOURCE: ${{format('clear;files,{0}\vcpkg-caches\windows-2022\binary,read;files,{0}\vcpkg-caches\{1}\binary,readwrite', github.workspace,matrix.runner) }}

      VCPKG_DEFAULT_BINARY_CACHE: ${{format('{0}\vcpkg-caches\{1}\binary', github.workspace,matrix.runner) }}
    
      
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
       submodules: true
  
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: Initial Setup
      run: |
        $vcpkgcfg_json = Get-Content vcpkg-configuration.json -Raw | ConvertFrom-Json
        [uint128]$vcpkghash = [UInt128]::Parse((Get-FileHash .\vcpkg-configuration.json -Algorithm Md5).Hash,'HexNumber') -bxor [UInt128]::Parse((Get-FileHash vcpkg.json -Algorithm Md5).Hash,'HexNumber')        
        mkdir "vcpkg-caches\windows-2022\asset" -force
        mkdir "vcpkg-caches\windows-2022\binary" -force
        mkdir "vcpkg-caches\${{matrix.runner}}\asset" -force
        mkdir "vcpkg-caches\${{matrix.runner}}\binary" -force
        # These multiline string is an embedded batch file that gets written out to use as a vcpkg asset cache script. 
        # Use this to enable reading from 2 caches. VCPKG only normally allows reading from 1 asset cache
        @'
        @echo off
        set esc=${{fromJSON('"\u001B"')}}
        set url=%1
        set sha512=%2
        set dst=%3
        set "_dst=%dst:/=\%"
        mkdir %_dst%
        rmdir %_dst%        
        cd /d "${{github.workspace}}\vcpkg-caches\windows-2022\asset"
        if exist %sha512% (
            echo %esc%[32mAsset cache hit in Windows-2022%esc%[0m
            copy %sha512% "%dst%"
            exit
        ) ELSE (
         echo %esc%[33mAsset cache miss in Windows-2022 will try ${{matrix.runner}}%esc%[0m
        )
        cd /d "${{github.workspace}}\vcpkg-caches\${{matrix.runner}}\asset"
        if exist %sha512% (
            echo %esc%[32mAsset cache hit in ${{matrix.runner}}%esc%[0m
            copy %sha512% "%dst%"
            exit
        ) ELSE (
          echo %esc%[33mAsset cache miss in ${{matrix.runner}} will download %url% %esc%[0m
        )
        curl.exe  --ssl-no-revoke --retry 5 --retry-delay 3 --retry-max-time 60 -L %url% --output .\%sha512%
        set "PSModulePath="
        powershell -command "if((Get-FileHash %sha512% -Algorithm SHA512 -erroraction SilentlyContinue).Hash -ne '%sha512%' ) {exit -1}" 
        if ERRORLEVEL 0 (
            echo %esc%[32mAsset cache SHA512 verify succeeded after download%esc%[0m
            copy .\%sha512% %_dst%
        ) ELSE (
            echo %esc%[31mAsset cache SHA512 verify failed after download%esc%[0m  
            del %sha512%
            exit /b -1
        )

        '@  | Out-File  "${{github.workspace}}\vcpkg-caches\asset-cache-script.bat"
        #disable last access time updating 
        fsutil behavior set disablelastaccess 1

        cd $Env:VCPKG_INSTALLATION_ROOT
        git fetch
        git checkout -f --detach $vcpkgcfg_json.'default-registry'.baseline
        .\bootstrap-vcpkg.bat
        ./vcpkg integrate install
        "CACHE_KEY=$env:ImageVersion#$vcpkghash"|Out-File -Append  ${{ github.env }}
        # download and install zstandard 1.5.7 to c:\windows so action caching works in windows-11-arm
        Invoke-WebRequest -Uri https://github.com/facebook/zstd/releases/download/v1.5.7/zstd-v1.5.7-win64.zip -OutFile zstd-v1.5.7-win64.zip
        Expand-Archive zstd-v1.5.7-win64.zip  -DestinationPath .
        Copy-Item zstd-v1.5.7-win64\zstd.exe c:\windows
        "MSBUILD_VERBOSITY=${{ case(runner.debug =='1','detailed','normal') }}"|Out-File -Append  ${{ github.env }}


    - name: Restore VCPKG windows-2022 Cache
      uses: actions/cache/restore@v5
      if: ${{ matrix.runner != 'windows-2022' }}
      id: vcpkg-2022-cache-restore
      with:
        path: vcpkg-caches/windows-2022
        key: vcpkg-cache-windows-2022-${{env.CACHE_KEY}}-${{github.sha}}-${{github.run_attempt}}
        restore-keys: |
          vcpkg-cache-windows-2022-${{env.CACHE_KEY}}
          vcpkg-cache-windows-2022
        enableCrossOsArchive: true

    - name: Restore VCPKG Cache
      uses: actions/cache/restore@v5      
      id: vcpkg-cache-restore
      with:
        path: vcpkg-caches/${{matrix.runner}}
        # Use the git rev hash of vcpkg in the cache key because things are not 
        # entirely compatible between versions
        key: vcpkg-cache-${{matrix.runner}}-${{env.CACHE_KEY}}-${{github.sha}}-${{github.run_attempt}}
        restore-keys: |
          vcpkg-cache-${{matrix.runner}}-${{env.CACHE_KEY}}
          vcpkg-cache-${{matrix.runner}}
        enableCrossOsArchive: true

       # If the cache key was not matched clean the cache and delete any file that isn't't acceessed by vcpkg        
       # do this by setting the last access time of ever file to jan 1st 2000 and then enable last access time updating
       # any file that was not accessed by the install_packages step gets deleted by the cache cleanup and hash step
    - name: Prepare for Cache Cleaning
      if: ${{ steps.vcpkg-cache-restore.outputs.cache-matched-key}}
      # && !contains( steps.vcpkg-cache-restore.outputs.cache-matched-key, env.CACHE_KEY) }}
      run: |
        $restorekey = '${{steps.vcpkg-cache-restore.outputs.cache-matched-key}}';
        $keyprefix = 'vcpkg-cache-${{matrix.runner}}-';
        $currentkey = '${{env.CACHE_KEY}}'
        $currenthash = $currentkey.Substring($env:ImageVersion.Length+1);
        $restorekey = $restorekey.Substring($keyprefix.Length)
        $separator = $restorekey.IndexOf('#')
        if($separator -eq -1){
        "failed to perse restore key string for image version no cache cleaning will be done"
        return 0 
        }
        $restorehash= $restorekey.Substring($separator+1,$currenthash.Length)

        $restoreversion = [semver]$restorekey.Substring(0,$separator);
        $currentversion = [semver]$env:ImageVersion;
        $hashmatched = $restorehash -eq $currenthash
        $currentnewer = $currentversion -gt $restoreversion;
        #only do it if the current image is newer than the cache or the hash didn't match
        if(-not $hashmatched -or $currentnewer){
          "Cache being cleaned. conditions met (currentnewer: $currentnewer, hashmatched: $hashmatched)"
          $longago = [DateTime]::Parse("2000-01-01") 
          get-ChildItem "vcpkg-caches\${{matrix.runner}}" -filter *.* -File | ForEach-Object { $_.LastAccessTimeUTC = $longago; $_.Name }
          fsutil behavior set disablelastaccess 0
        }else {
          "Cache not being cleaned. conditions not met (currentnewer: $currentnewer, hashmatched: $hashmatched) "
        }

    - name: Install VCPKG packages for configurations (${{env.BUILD_CONFIGURATIONS}}) and platforms (${{env.BUILD_PLATFORMS}})
      id: install_packages
      run: |      
        #immediately fail the script on any error
        $PSNativeCommandUseErrorActionPreference = $true
        $ErrorActionPreference = 'Stop'

        foreach($configuration  in $ENV:BUILD_CONFIGURATIONS.Split(" ",[System.StringSplitOptions]::RemoveEmptyEntries)) {
          foreach($platform  in $ENV:BUILD_PLATFORMS.Split(" ",[System.StringSplitOptions]::RemoveEmptyEntries)) {
            echo "`e[34m$platform $configuration`e[0m"
            
            msbuild /v:${{ env.MSBUILD_VERBOSITY }} /p:Configuration=$configuration /p:Platform=$platform ${{env.SOLUTION_FILE_PATH}} /t:${{env.TARGET_VCPKG_MANIFEST_INSTALL}} ${{env.MSBUILD_EXTRA_OPTIONS}}
          }
        }

      # Hash the cache and delete any unaccessed files. Only need to hash the filenames
      # asset cache filenames are a sha512 has of the contents. binary cache filenames are unique identifer of what the file contents should be.
      # Unaccessed files are only deleted if the install_packages step succeeded because the step might have failed before the files would have been accesssed
    - name: Cleanup and Hash Cache
      if: ${{ always() }}
      run: |
        fsutil behavior set disablelastaccess 1
        chdir "vcpkg-caches\${{matrix.runner}}"    
        $longago = [DateTime]::Parse("2000-01-01") 
        $failed = ${{case(steps.install_packages.outcome != 'success','$true','$false')}}
        $hash = 0
        $oldhash = Get-Content hash -ErrorAction ignore
        Remove-item hash -ErrorAction Ignore
        get-ChildItem -Recurse . | ForEach-Object{
            if ($_.LastAccessTimeUtc -eq $longago -and -not $failed){
                Remove-Item $_ -Force -Verbose
            }
            else {
                $relativename = Resolve-Path $_.FullName -Relative
                $stringAsStream = [System.IO.MemoryStream]::new()
                $writer = [System.IO.StreamWriter]::new($stringAsStream)
                $writer.Write($relativename)
                $writer.Flush()
                $stringAsStream.Position = 0                
                $hash = $hash -bxor [UInt128]::Parse((Get-FileHash -InputStream $stringAsStream -Algorithm Md5).Hash,'HexNumber')
            }
        }
        echo "old hash was $oldhash"            
        echo "new hash is  $hash"
        #write the new has out to a file to be store in the cache
        $hash|Out-File hash
        
        # on failure of install_packages step set the hash to the valuethe outcome of the step
        # this will cause the cache to be always saved on failure
        if ($failed){
          $hash = '${{steps.install_packages.outcome}}'
        }

        if ($hash -ne $oldhash){ 
          "VCPKG_CACHE_HASH=$hash"|Out-File -Append ${{ github.env }} 
        }
      
    # cache is only saved if the hash was set in the previous step. If the hash wasn't set there were no changes to the cache
    - name: Save VCPKG cache
      if: ${{ always() && env.VCPKG_CACHE_HASH}}
      id: vcpkg-cache-save
      uses: actions/cache/save@v5
      with:
        path: vcpkg-caches/${{ matrix.runner }}
        key: vcpkg-cache-${{ matrix.runner }}-${{env.CACHE_KEY}}-${{github.sha}}-${{github.run_attempt}}-${{env.VCPKG_CACHE_HASH}}
        enableCrossOsArchive: true
  
    - name: Build Solution for configurations (${{env.BUILD_CONFIGURATIONS}}) and platforms (${{env.BUILD_PLATFORMS}})
      run: |
        #immediately fail the script on any error
        $PSNativeCommandUseErrorActionPreference = $true
        $ErrorActionPreference = 'Stop'

        foreach($configuration  in $ENV:BUILD_CONFIGURATIONS.Split(" ",[System.StringSplitOptions]::RemoveEmptyEntries)){
          foreach($platform  in $ENV:BUILD_PLATFORMS.Split(" ",[System.StringSplitOptions]::RemoveEmptyEntries)){
            echo "`e[34m$platform $configuration`e[0m"
            
            msbuild /v:${{ env.MSBUILD_VERBOSITY }} /p:Configuration=$configuration /p:Platform=$platform ${{env.SOLUTION_FILE_PATH}} ${{env.MSBUILD_EXTRA_OPTIONS}}
            # clean the output so nothing is left that might influence other builds
            msbuild /v:${{ env.MSBUILD_VERBOSITY }} /p:Configuration=$configuration /p:Platform=$platform ${{env.SOLUTION_FILE_PATH}} /t:clean ${{env.MSBUILD_EXTRA_OPTIONS}}
          }
        }
      
      
      

